// Generated by CoffeeScript 1.3.3

dojo.provide('app.header.RepositoryDialog');

dojo.require('dijit._Templated');

dojo.require('dijit.Dialog');

dojo.require('dijit.form.Form');

dojo.require('dijit.form.TextBox');

dojo.require('dijit.form.Button');

dojo.declare('app.header.RepositoryDialog', [dijit.Dialog, dijit._Templated], {
  templateString: dojo.cache('app.header', 'templates/RepositoryDialog.html'),
  widgetsInTemplate: true,
  title: 'Add New Repository',
  style: 'width:500px',
  constructor: function() {
    return this.inherited(arguments);
  },
  postCreate: function() {
    this.inherited(arguments);
    dojo.connect(this.domRegister, 'onClick', this, this.register);
    dojo.connect(this.domCancel, 'onClick', this, this.onCancel);
    dojo.connect(this.domFormName, 'onKeyUp', this, this.updateRegisterButton);
    return dojo.connect(this.domFormPath, 'onKeyUp', this, this.updateRegisterButton);
  },
  updateRegisterButton: function() {
    if (this.domFormName.getValue() === '' || this.domFormPath.getValue() === '') {
      return this.domRegister.setDisabled(true);
    } else {
      return this.domRegister.setDisabled(false);
    }
  },
  show: function() {
    this.inherited(arguments);
    this.domFormName.setValue('');
    this.domFormPath.setValue('');
    return this.domRegister.setDisabled(true);
  },
  register: function() {
    var data;
    data = this.domForm.getValues();
    dojo.publish('DataManager/fetch', [
      'addRepository', {
        context: this,
        postdata: {
          newRepoName: data.name,
          newRepoPath: data.path
        }
      }, function(data) {
        var repo;
        repo = data.repository;
        dojo.publish('layout/LAN/addCommonNotice', [data.repository + ' リポジトリを追加しました']);
        dojo.publish('layout/Header/setRepositoryMenu');
        dojo.publish('layout/Header/setRepository', [repo]);
        return this.hide();
      }
    ]);
    return console.log(this.domForm, data);
  }
});
