// Generated by CoffeeScript 1.3.3

dojo.provide('app.layout.Common');

dojo.declare('app.layout.Common', [], {
  style: 'width:100%; height:100%; border:1px solid #aaa; background-color:#eee; padding:8px;'
});
