// Generated by CoffeeScript 1.3.3

dojo.provide('app.layout.Left');

dojo.require('dijit.layout.AccordionContainer');

dojo.require('dijit.layout.AccordionPane');

dojo.require('dijit._Widget');

dojo.require('dijit._Templated');

dojo.declare('app.layout.Left', [dijit._Widget, dijit._Templated], {
  widgetsInTemplate: true,
  templateString: dojo.cache('app.layout', 'templates/Left.html'),
  constructor: function() {
    this.inherited(arguments);
    return console.log('layout/Left.coffee : constructor');
  },
  postCreate: function() {
    return this.inherited(arguments);
  }
});
