// Generated by CoffeeScript 1.3.3

dojo.provide('app.layout.Side');

dojo.require('app.list.CommitList');

dojo.require('dijit.layout.AccordionContainer');

dojo.require('dijit.layout.ContentPane');

dojo.require('dijit._Widget');

dojo.require('dijit._Templated');

dojo.declare('app.layout.Side', [dijit.layout._LayoutWidget, dijit._Templated], {
  widgetsInTemplate: true,
  templateString: dojo.cache('app.layout', 'templates/Side.html'),
  style: 'width:400px; height:100%; border:0; padding:0;',
  resize: function() {
    this.inherited(arguments);
    return this.accordionContainer.resize();
  }
});
