// Generated by CoffeeScript 1.3.3

dojo.provide('app.list.CommitListUnit');

dojo.require('dijit._WidgetBase');

dojo.require('dijit._Templated');

dojo.declare('app.list.CommitListUnit', [dijit._Widget, dijit._Templated], {
  widgetsInTemplate: true,
  templateString: dojo.cache('app.list', 'templates/CommitListUnit.html'),
  style: 'width:100%;',
  data: null,
  selected: false,
  constructor: function(data) {
    this.inherited(arguments);
    this.data = data;
    return dojo.publish('Mediater/register', ['list/CommitListUnit/selectCommit', this, this.onSelectCommit]);
  },
  postCreate: function() {
    dojo.connect(this.domInner, 'onmouseenter', this, function() {
      if (!this.selected) {
        return $(this.domInner).css('backgroundColor', '#eee');
      }
    });
    dojo.connect(this.domInner, 'onmouseleave', this, function() {
      if (!this.selected) {
        return $(this.domInner).css('backgroundColor', '#fff');
      }
    });
    return dojo.connect(this.domInner, 'click', this, function() {
      return dojo.publish('Mediater/call', ['list/CommitListUnit/selectCommit', [this.data]]);
    });
  },
  onSelectCommit: function(commit) {
    console.log('onSelectCommit', commit[0]);
    if (this.data === commit[0]) {
      this.selected = true;
      return $(this.domInner).css('backgroundColor', '#dfd');
    } else {
      this.selected = false;
      return $(this.domInner).css('backgroundColor', '#fff');
    }
  }
});
