// Generated by CoffeeScript 1.3.3

dojo.provide('app.App');

dojo.require('app.layout.LayerAndNotice');

dojo.require('app.layout.Header');

dojo.require('app.layout.Center');

dojo.require('app.layout.Side');

dojo.require('app.DataManager');

dojo.require('dijit.layout._LayoutWidget');

dojo.require('dijit._Templated');

dojo.require('dijit.layout.BorderContainer');

dojo.declare('app.App', [dijit.layout._LayoutWidget], {
  components: {
    layer: null,
    main: null,
    header: null,
    center: null,
    side: {
      left: null,
      right: null
    }
  },
  datamanager: null,
  constructor: function() {
    this.components.layer = new app.layout.LayerAndNotice;
    dojo.publish('layout/LAN/fadeIn', ['初期化処理を実行中']);
    return this.datamanager = new app.DataManager;
  },
  postCreate: function() {
    this.inherited(arguments);
    this.initializeLayout();
    this.initializeComponents();
    dojo.publish('layout/LAN/setNotice', ['ロード完了']);
    return dojo.publish('layout/LAN/fadeOut');
  },
  initializeLayout: function() {
    dojo.publish('layout/LAN/setNotice', ['画面レイアウトを構築中']);
    $('body').append('<div id="container"></div>');
    this.components.main = new dijit.layout.BorderContainer({
      style: 'width:100%; height:100%;',
      design: 'headline'
    }, 'container');
    this.components.main.addChild(this.components.header = new app.layout.Header({
      region: 'top',
      style: 'margin-bottom:0;'
    }));
    this.components.main.addChild(this.components.center = new app.layout.Center({
      region: 'center'
    }));
    this.components.main.addChild(this.components.side.left = new app.layout.Side({
      region: 'left',
      splitter: 'true'
    }));
    this.components.main.startup();
    return this.components.side.left.accordionContainer.resize();
  },
  initializeComponents: function() {
    return this.components.header.initialize();
  }
});
