// Generated by CoffeeScript 1.3.3

dojo.provide('app.App');

dojo.require('app.layout.Header');

dojo.require('app.layout.Center');

dojo.require('app.layout.Left');

dojo.require('dijit.layout._LayoutWidget');

dojo.require('dijit._Templated');

dojo.require('dijit.layout.ContentPane');

dojo.require('dijit.layout.BorderContainer');

dojo.require('dijit.layout.AccordionContainer');

dojo.require('dijit.layout.AccordionPane');

dojo.require('dijit.layout.TabContainer');

dojo.declare('app.App', [], {
  components: {
    header: null,
    left: {
      top: null,
      center: null
    },
    center: null
  },
  constructor: function() {
    this.inherited(arguments);
    console.log('App.coffee : constructor');
    return this.setLayout();
  },
  setLayout: function() {
    var bc, lefts;
    $('body').append('<div id="container"></div>');
    bc = new dijit.layout.BorderContainer({
      style: 'width:100%; height:100%;',
      design: 'headline'
    }, 'container');
    this.components.header = new app.layout.Header({
      region: 'top',
      style: 'margin-bottom:0;'
    });
    lefts = new dijit.layout.BorderContainer({
      region: 'left',
      style: 'width:360px; style="height:100%;" border:0;',
      splitter: 'true'
    });
    this.components.left.top = new app.layout.Left({
      region: 'top',
      style: 'height:30%; border:0;',
      splitter: 'true'
    });
    this.components.left.center = new app.layout.Left({
      region: 'center',
      style: 'border:0;',
      splitter: 'true'
    });
    this.components.center = new app.layout.Center({
      region: 'center',
      splitter: 'true'
    });
    bc.addChild(this.components.header);
    bc.addChild(lefts);
    lefts.addChild(this.components.left.top);
    lefts.addChild(this.components.left.center);
    bc.addChild(this.components.center);
    return bc.startup();
  }
});
