// Generated by CoffeeScript 1.3.3

dojo.provide('app.App');

dojo.require('app.layout.Header');

dojo.require('app.layout.Center');

dojo.require('app.layout.Side');

dojo.require('dijit.layout._LayoutWidget');

dojo.require('dijit._Templated');

dojo.require('dijit.layout.BorderContainer');

dojo.declare('app.App', [dijit.layout._LayoutWidget], {
  components: {
    main: null,
    header: null,
    center: null,
    side: {
      left: null,
      right: null
    }
  },
  postCreate: function() {
    this.inherited(arguments);
    return this.setLayout();
  },
  setLayout: function() {
    $('body').append('<div id="container"></div>');
    this.components.main = new dijit.layout.BorderContainer({
      style: 'width:100%; height:100%;',
      design: 'headline'
    }, 'container');
    this.components.main.addChild(this.components.header = new app.layout.Header({
      region: 'top',
      style: 'margin-bottom:0;'
    }));
    this.components.main.addChild(this.components.center = new app.layout.Center({
      region: 'center'
    }));
    this.components.main.addChild(this.components.side.left = new app.layout.Side({
      region: 'left',
      splitter: 'true'
    }));
    this.components.main.startup();
    return this.components.side.left.accordionContainer.resize();
  }
});
